services:
  - type: worker
    name: telegram-gpt-agent
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python3 main.py
    runtime: python
    region: oregon
    pythonVersion: 3.10.11